### ISSUE TITLE
timer services data.duration

### ISSUE THREAD

**Issue by dennis77pr** [Ellisande/kanbonsai#6]
I am trying to figure out the timer service and I can't figure out where the functions called by the socket.on methods are getting the data.duration object.  Where is that object being populated from?  It is always set to 3 minutes even when the duration attribute is set to something else.  

Thanks for the help

**Comment by Ellisande** [comment]
Hi Dennis, 

Just a quick recap of the functionality. In all phases except discuss, the timer does not decrease, its a fixed 3:00 minute timer. Once you are on discuss each topic has it own associated timer that decreases the total time by half each time it runs out.

They get populated by the 'timer' events from the server. For instance: 
```javascript
// server.js - timer init
socket.emit('timer:init', {
   duration: meeting.getTimer().asMilliseconds()
});
```
```javascript 
//server-meeting.js getDiscussTimer (delegated by getTimer())
this.getDiscussPhaseTimer = function(meeting){
   var currentTopic = this.getCurrentTopic();
   if(!currentTopic) return moment.duration(0, 'seconds');
   return currentTopic.timer;
};
```

The key here is that the duration is set by meeting.getTimer() before the discuss phase, and meeting.getDiscussTimer() in the discuss phase, so the underlying objects are what actually drives the timer, and that's where the logic for it is. In the discuss phase you should see the timer coming back at 3:00 (the default) unless you have stopped the timer, then it should reduce by half. The code for that is in the model.js topic object:

```javascript
//model.js - topic object
this.reset = function(){
   this.continue = [];
   this.stop = [];
   this.timer = moment.duration(this.timer.minutes() / 2, 'minutes');
};
```

**Comment by dennis77pr** [comment]
Ah, now I get it.  Thanks for the explanation.  This info helped a ton!
